### ISSUE TITLE
Request Failure when using data

### ISSUE THREAD

**Issue by lawrence615** [DWorkS/VolleyPlus#10]
Hi, 

I successfully implemented a SimpleMultiPartRequest  with both string and file params; file param is optional in my case.

But now the issue is, my  requests keep failing whenever am using data(edge or 3G) not wifi; in fact it is very fast on wifi. I have to resubmit severally for it to work.

I have tried increasing the time in retry policy but still not working. Other requests(JsonObjectRequest and JsonArrayRequest) are however ok.

What could be the issue here?

Thanks

**Comment by 1hakr** [comment]
@lawrence615 if you can post the actual code, i can debug and try figuring out the issue.

**Comment by lawrence615** [comment]
@1hakr here is the code  excerpt showing the http request
```
protected void makeHttpRequestToPostFeedback2(String title, String message)
			throws IOException {

		showProgress();

		System.err.println(longitude);

		SimpleMultiPartRequest request = new SimpleMultiPartRequest(
				Method.POST, AppConstants.postFeedback, reqSuccessListener(),
				reqErrorListener()) {
			@Override
			public Map<String, String> getHeaders() throws AuthFailureError {
				HashMap<String, String> headers = new HashMap<String, String>();
				headers.put("Accept", "application/json");
				headers.put("Content-Length", "302");
				return headers;
			}
		};
		request.addMultipartParam("user_id", "text/plain",
				Integer.toString(getUserId()));
		request.addMultipartParam("tag_id", "text/plain", Integer.toString(16));
		request.addMultipartParam("county_id", "text/plain",
				Integer.toString(getCountyId()));
		request.addMultipartParam("title", "text/plain", title);
		request.addMultipartParam("message", "text/plain", message);
		request.addMultipartParam("latitude", "text/plain",
				Double.toString(latitude));
		request.addMultipartParam("longitude", "text/plain",
				Double.toString(longitude));

		if (mImageView.getDrawable() != null) {
			File f = createImageFile();
			// request.addFile("image_url",
			// "/storage/emulated/0/Pictures/IRDAC/IMG_20150121_142054_-387625257.jpg");
			request.addFile("image_url", photo_path_to_send_to_server);
			System.out.println("image_url " + photo_path_to_send_to_server);
		}
		RequestQueue mRequestQueue = Volley.newRequestQueue(getActivity());
		request.setShouldCache(false);
		request.setRetryPolicy(new DefaultRetryPolicy((int) TimeUnit.SECONDS
				.toMillis(40), DefaultRetryPolicy.DEFAULT_MAX_RETRIES,
				DefaultRetryPolicy.DEFAULT_BACKOFF_MULT));
		mRequestQueue.add(request);
		mRequestQueue.start();

	}
```

**Comment by 1hakr** [comment]
I cant debug with this, i need the actual endpoint.

**Comment by lawrence615** [comment]
What do you mean the actual endpoint?

**Comment by 1hakr** [comment]
the actual url

**Comment by lawrence615** [comment]
Ok, but I will have to email you because the api is not yet secured. I will use this email address hakr@dworks.in

**Comment by lawrence615** [comment]
Hi @1hakr , I think I have managed to solve the problem. 

If you look at my request, I had put the Content-Length entity-header; I removed this and the request is fast when using both wifi and data.

Thanks

**Comment by 1hakr** [comment]
Cool. I though you put it for a reason.

**Comment by lawrence615** [comment]
Yes I had a reason; I had put it initially when I was testing with a static file but then I forgot to remove it
