### ISSUE TITLE
Android Studio Gradle Sync Error

### ISSUE THREAD

**Issue by krialix** [DWorkS/VolleyPlus#13]
Error:Artifact 'volleyplus.jar (dev.dworks.libs:volleyplus:0.1.2)' not found.
Searched in the following locations:
    https://jcenter.bintray.com/dev/dworks/libs/volleyplus/0.1.2/volleyplus-0.1.2.jar

**Comment by 1hakr** [comment]
can you post your build.gradle code?

**Comment by krialix** [comment]
apply plugin: 'com.android.application'

android {
    compileSdkVersion 21
    buildToolsVersion "21.1.2"

    defaultConfig {
        applicationId "com.krialix.interpalsplus"
        minSdkVersion 15
        targetSdkVersion 21
        versionCode 1
        versionName "1.0"
    }
    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro'
        }
    }
}

dependencies {
    compile fileTree(include: ['*.jar'], dir: 'libs')
    compile 'com.android.support:appcompat-v7:21.0.+'
    compile 'com.android.support:recyclerview-v7:21.0.+'
    compile 'com.android.support:cardview-v7:21.0.+'
    compile 'com.jpardogo.materialtabstrip:library:1.0.+'
    compile 'com.rengwuxian.materialedittext:library:1.8.+'
    compile 'dev.dworks.libs:volleyplus:+'
    compile 'org.jsoup:jsoup:1.8.1'
}

**Comment by 1hakr** [comment]
what are the repositories from which dependencies are resolved?

**Comment by krialix** [comment]
// Top-level build file where you can add configuration options common to all sub-projects/modules.

buildscript {
    repositories {
        jcenter()
    }
    dependencies {
        classpath 'com.android.tools.build:gradle:1.0.1'

        // NOTE: Do not place your application dependencies here; they belong
        // in the individual module build.gradle files
    }
}

allprojects {
    repositories {
        jcenter()
    }
}

**Comment by krialix** [comment]
I solved the problem by reinstalling Android Studio. Now it works :)

**Comment by hashimyfareed** [comment]
i cannot sync. It fails to resolve compile 'dev.dworks.libs:volleyplus:+'. please help. thanks.

**Comment by nderituKelvin** [comment]
Try unchecking the "offline work" gradle settings
It worked for @krialix because installing it again came with the setting having been reset
