### ISSUE TITLE
Remove trailing '&' when constructing URL for GET request

### ISSUE THREAD

**Issue by rbachyk** [DWorkS/VolleyPlus#19]
In Request.java, method getEncodedUrlParams() constructs URL for GET method, but it always contain trailing '&' symbol, so request fails with such url.
It could be easily fixed by removing last symbol from encodedParams.

**Comment by 1hakr** [comment]
This is part of the main volley library from google. The failure is dependent on the how the server is implemented. I would suggest you extend Request and remove the trailing '&'.
