### ISSUE TITLE
Confused about which to import

### ISSUE THREAD

**Issue by newjing** [DWorkS/VolleyPlus#20]
I found there's a subfolder "plus" everywhere.
E.g. for  "SimpleImageLoader",   shall I import 
        "com.android.cache.SimpleImageLoader"
or     "com.android.cache.plus.SimpleImageLoader"  ???
I compared two files and there're minor differences, which one is the correct one to use?

BTW, could you pls add an example to show how to use onProgress in upload/download ?

**Comment by 1hakr** [comment]
```com.android.cache.SimpleImageLoader``` is the default one which you should use. The plus one is experimental, not fully done yet. 

Regarding the onProgress example, i will add an example soon.
