### ISSUE TITLE
How to use RequestTickle

### ISSUE THREAD

**Issue by thevirus20** [DWorkS/VolleyPlus#22]
Hi,
I am getting ```RequestTickle.start: Unhandled exception android.os.NetworkOnMainThreadException```.
How can I use ```RequestTickle``` to perform sync request?

I used your sample to test.
```java
RequestTickle mRequestTickle = VolleyTickle.newRequestTickle(getApplicationContext());

StringRequest stringRequest = new StringRequest(Request.Method.GET, url, null, null);
mRequestTickle.add(stringRequest);
NetworkResponse response = mRequestTickle.start();

if (response.statusCode == 200) {
    String data = VolleyTickle.parseResponse(response);
    Log.i("Response",data);
}
else{
    Log.e("error",mRequestTickle.getError().getMessage());
}
```

Using this in ```AsyncTask<>```  gives the response.Do I need to include the call in ```AsyncTask``` to work?Then how can I get and return the response?

Note : Works also if ThreadPolicy is set to permitAll.

**Comment by 1hakr** [comment]
Request Tickle is not supposed to be run on main thread. AsyncTask is the correct way to use Tickle. In AsyncTask `doInBackground()` method retun the string and you can process it in `onPostExecute()`

**Comment by thevirus20** [comment]
After going through readme that It is mainly useful for sync operation, I thought that I can wait for response after sending request with Request Tickle.
Can you tell me how can I wait for response after sending request?
I want something like this:
```java
String response = sendrequest(url);//sending a String post request on url and returns response 
````

Thanks.

**Comment by PurTahan** [comment]
HI,

why my Code Doesn't work? Never Response Status Code is 200!


        String tag_json_obj = "shahid";
        String url = "http://yad.ptapp.ir/core/v1/shahid";
        final dialogLoadingWithAdad loading=new dialogLoadingWithAdad(App.getContext());

        RequestTickle mRequestTickle = VolleyTickle.newRequestTickle(App.getContext());

        StringRequest stringRequest = new StringRequest(Request.Method.POST, url, null, null)
        {

            @Override
            protected Map<String,String> getParams(){
                Map<String,String> params = new HashMap<>();
                params.put("ShahidID","0");
                return params;
            }

        }
                ;


        mRequestTickle.add(stringRequest);
        NetworkResponse response = mRequestTickle.start();

        if (response.statusCode == 200) {
            String data = VolleyTickle.parseResponse(response);

            try {
                JSONObject jres=new JSONObject(data);
                if(jres.getInt("ID")>-1){

                    db.execute("insert into Shahid(ID,Nam,Famil,Pedar,tTavalod," +
                            "mTavalod,tShahadat,mShahadat,Aramgah) values(@0,@1,@2," +
                            "@3,@4,@5,@6,@7,@8)" , new Object[]{
                            jres.getInt("ID"),
                            jres.getString("Nam"),
                            jres.getString("Famil"),
                            jres.getString("Pedar"),
                            jres.getString("tTavalod"),
                            jres.getString("mTavalod"),
                            jres.getString("tShahadat"),
                            jres.getString("mShahadat"),
                            jres.getString("Aramgah")
                    });

                    db.QueryValue("insert into ShahidRuz(Shahid,Tarikh) values(@0,@1)",
                            new String[]{""+jres.getInt("ID"), tools.NowShamsi()});

                    return new cShahid(jres.getInt("ID"));
                }
            } catch (JSONException e) {
                e.printStackTrace();
                return null;
            }
        }
        else{
            return null;
        }

**Comment by 1hakr** [comment]
@PurTahan , you need to call ```mRequestTickle.start()``` from another thread and not from the main thread. Use async task to solve this issue.

**Comment by bitsnaps** [comment]
Here is a quick way to use RequestTicke with AsyncTask:
`
    public static final String URL = "http://...";
    public static final String TAG = "...";

    private class AsyncExecute extends AsyncTask<String, Void, String> {

        RequestTickle tickle;
        StringRequest req;

        @Override
        protected String doInBackground(String... params) {
            tickle = VolleyTickle.newRequestTickle(getApplicationContext());
            req = new StringRequest(Request.Method.GET, params[0], null, null);
            tickle.add(req);
            NetworkResponse response = tickle.start();
            if (response.statusCode==HTTP_OK) {
                String data = VolleyTickle.parseResponse(response);
                return data;
            }
            return "";
        }

        @Override
        protected void onPostExecute(String response) {
            if (response.isEmpty()) {
                Log.e(TAG, tickle.getError().getMessage());
            } else {
                Log.d(TAG, response);
            }
        }

    }

    public void tickleRequest(View v){
        new AsyncExecute().execute(URL);
    }`

**Comment by ShiiVa03** [comment]
Bela merda!
