### ISSUE TITLE
Image quality

### ISSUE THREAD

**Issue by kikko088** [DWorkS/VolleyPlus#24]
I use this code for show an image from an URL, the problem is the image quality that is not so good, there is a way for improve the image quality?

NetworkImageViewPlus mNetworkImageView;
mNetworkImageView = (NetworkImageViewPlus) viewLayout.findViewById(R.id.networkImageView);
mNetworkImageView.setAdjustViewBounds(true);
mNetworkImageView.setScaleType(ImageView.ScaleType.CENTER_CROP);
mNetworkImageView.setImageUrl(DataSource.base_url + string, mImageLoader);
mNetworkImageView.setDefaultImageResId(R.drawable.no_image);
mNetworkImageView.setErrorImageResId(R.drawable.no_image);

**Comment by 1hakr** [comment]
It will depend on the ```mImageLoader``` mostly. Can you post the code for ImageLoader aswell?
