### ISSUE TITLE
How can i set ProgressListener to MultiPartRequest?

### ISSUE THREAD

**Issue by epolar** [DWorkS/VolleyPlus#31]
Anywhere i can set ProgressListener whit MultiPartRequest or SimpleMultiPartRequest?Maybe MultiPartRequest need a setProgressListener(ProgressListener listener) function.

**Comment by fahmihidayah** [comment]
use SimpleMultiPartRequest and override onProgress(). and there are two parameters  transferredBytes,  totalSize then set progres your ProgressDialog on that method.

**Comment by epolar** [comment]
Thinks. @fahmihidayah , it work.
