### ISSUE TITLE
Requests do not follow 301 and 302 redirection

### ISSUE THREAD

**Issue by JordanGout** [DWorkS/VolleyPlus#34]
There is an solution you can here : http://stackoverflow.com/questions/17481964/android-volley-to-handle-redirect/17483037#17483037

**Comment by 1hakr** [comment]
fixed in the latest version

**Comment by ashoksinghal** [comment]
I am requesting an url with http and it redirects to https via 302

**Comment by fedyshyn1994** [comment]
"fixed in the latest version" - it is not work.(((((

**Comment by fedyshyn1994** [comment]
@1hakr "fixed in the latest version" - it is not work.(((((
