### ISSUE TITLE
Is this library using up to date Volley source code?

### ISSUE THREAD

**Issue by dcgavril** [DWorkS/VolleyPlus#35]
I was wondering if this library is a plus to the current Google Volley library(so, using the Volley library as an up to date core), or it uses an old version of that library and it has couple of improvements.
Anyway, can you tell me when was the last time the core library was updated to the version delivered by Google on their git host?

Thanks!

**Comment by 1hakr** [comment]
It is restructured Volley library with lot of improvements. Its updated regularly. The current code is up-to-date with the original Volley library
