### ISSUE TITLE
example for video

### ISSUE THREAD

**Issue by baneizalfe** [DWorkS/VolleyPlus#37]
Hi
in your documentation you specified that imagecache-ing supports among other video cache-ing. Can you provide a example?

**Comment by 1hakr** [comment]
```
ImageView mImageView;
String path = "video file path";
mImageLoader.get("video://" + path, mImageView);
```

**Comment by jinsen47** [comment]
Hi, this example is for local file right?
how about a file on server, thru http protocol?
