### ISSUE TITLE
bug in NetworkImageViewPlus

### ISSUE THREAD

**Issue by DJafari** [DWorkS/VolleyPlus#43]
i found a bug in `NetworkImageViewPlus` when `setFadeInImage` is true

in this file : 
https://github.com/DWorkS/VolleyPlus/blob/master/library/src/com/android/volley/ui/NetworkImageViewPlus.java#L257

you must remove : `setImageDrawable(null);`

**Comment by 1hakr** [comment]
fixed in latest version
