### ISSUE TITLE
addMultipartParam

### ISSUE THREAD

**Issue by cyq7on** [DWorkS/VolleyPlus#44]
How to use method "addMultipartParam",can you give me a example?
I need to add the string parameters of a multipart request，also，I want to upload files.
Those are what I must to add:
params.put("source", val1);
params.put("access_token", val2);
params.put("status", val3);
Can you understand me?

**Comment by cnbuff410** [comment]
SimpleMultiPartRequest request = new SimpleMultiPartRequest(xxxxx...)
request.addFile("file", fullFileName);
request.addMultipartParam("testKey", "text/plain", "testValue");
request.addMultipartParam("testKey1", "text/plain", "testValue1");

**Comment by cyq7on** [comment]
Here are my codes:
SimpleMultiPartRequest request = new SimpleMultiPartRequest(
                            Constants.STATUSES_UPLOAD, new Response.Listener<String>() {
                        @Override
                        public void onResponse(String response) {
                            ToastUtil.showShort(PublishActivity.this, "成功");
                            finish();
                        }
                    }, new Response.ErrorListener() {
                        @Override
                        public void onErrorResponse(VolleyError error) {
                            ToastUtil.showShort(PublishActivity.this, error.getMessage());
                        }
                    });
request.addFile("pic", path);
request.addMultipartParam("source", "text/plain", Constants.APP_KEY);
request.addMultipartParam("access_token", "text/plain", accessToken.getToken());
request.addMultipartParam("status", "text/plain", content);
requestQueue.add(request);
but I get BasicNetwork.performRequest: Unexpected response code 400,what happened?

**Comment by cnbuff410** [comment]
The first param of your SimpleMultiPartRequest should be the destination URL.

**Comment by cyq7on** [comment]
Constants.STATUSES_UPLOAD is a URL

**Comment by AhmadullahSaikat** [comment]
I got the same error.......  can anyone help me?
