### ISSUE TITLE
Not able to remove cahed responses.

### ISSUE THREAD

**Issue by karthikvdhanya** [DWorkS/VolleyPlus#65]
My application doesnot require casched respose. Since i need to fetch data freequently, and data in the server varies constatnly . But through this library , I am always getting chached response . 

I have tried 

`getRequestQueue().getCache().flush();
        getRequestQueue().getCache().clear();
        getRequestQueue().getCache().close();
        getRequestQueue().getCache().remove(req.getCacheKey());
        getRequestQueue().getCache().invalidate(req.getCacheKey(),true);`

All these, still I am getting only cached response

**Comment by 1hakr** [comment]
Did you get it working ? if not then this is the right way 
`request.setShouldCache(true);`
