### ISSUE TITLE
MultipartReqest Example

### ISSUE THREAD

**Issue by rambabupudari** [DWorkS/VolleyPlus#7]
Can you provide any example to upload image on server(Multipart request).i didnt find any example.
Please help me..
Thanx in advance.

**Comment by 1hakr** [comment]
SimpleMultipartRequest request = new MultipartRequest(Method.POST, apiUrl, mListener, mErrorListener);
        request.addFile("photo", image_path);
        RequestQueue mRequestQueue = Volley.newRequestQueue(getApplicationContext());
        mRequestQueue.addRequest(request);
        mRequestQueue.start();

**Comment by rambabupudari** [comment]
bro this is deprecated request.

**Comment by 1hakr** [comment]
Can you specify what is deprecated here? Is it the class or any method in this class?

**Comment by rambabupudari** [comment]
MultipartRequest class showing ad depricated.

**Comment by 1hakr** [comment]
I have updated the example code, try it now.

**Comment by rambabupudari** [comment]
Thank you bro.but if i ave multipleparams like date,subject,id,name......

how can you i send these params with file

**Comment by 1hakr** [comment]
request.addMultipartParam("key", "text/plain", "value");

**Comment by rambabupudari** [comment]
thanq bro.by made it with my own request like below
public class MultipartRequest extends Request<String> {

   MultipartEntityBuilder entity = MultipartEntityBuilder.create();

    private final Response.Listener<String> mListener;
    private final Map<String, String> mStringParts;
    private final Map<String, File> mFileParts;
byte[] data;

    public MultipartRequest(String url, Response.Listener<String> listener,
            Response.ErrorListener errorListener,
            Map<String, String> stringParts, byte[] data) {
        super(Method.POST, url, errorListener);
this.data=data;
        mListener = listener;
        mStringParts = stringParts;
        mFileParts = fileParts;
        buildMultipartEntity();
    }

    private void buildMultipartEntity() {
        for (Map.Entry<String, String> entry : mStringParts.entrySet()) {
            try {
                entity.addPart(entry.getKey(), new StringBody(entry.getValue()));
            } catch (UnsupportedEncodingException e) {
                VolleyLog.e("UnsupportedEncodingException");
            }
        }

      
          entity.addBinaryBody("key", data, ContentType.create("image/png"), "image.png");
      
    }

    @Override
    public String getBodyContentType() {
        return entity.getContentType().getValue();
    }

    public MultipartEntity getEntity() {
        return entity.build().;
    }

    @Override
    protected Response<String> parseNetworkResponse(NetworkResponse response) {
        return Response.success("Uploaded", getCacheEntry());
    }

    @Override
    protected void deliverResponse(String response) {
        mListener.onResponse(response);
    }
}



/////////////////////////////////////////////////////////////////////////////////////////////
public class MultiPartStack extends HurlStack {
    private final static String HEADER_CONTENT_TYPE = "Content-Type";

    @Override
    public HttpResponse performRequest(Request<?> request, Map<String, String> additionalHeaders)
            throws AuthFailureError, IOException {
        if (!(request instanceof MultipartRequest)) {
            return super.performRequest(request, additionalHeaders);
        }
        HttpPost httpRequest = new HttpPost(request.getUrl());
        httpRequest.addHeader(HEADER_CONTENT_TYPE, request.getBodyContentType());
        setMultiPartBody(httpRequest, request);
        addHeaders(httpRequest, additionalHeaders);
        addHeaders(httpRequest, request.getHeaders());
        HttpParams httpParams = httpRequest.getParams();
        int timeoutMs = request.getTimeoutMs();
        HttpConnectionParams.setConnectionTimeout(httpParams, 5000);
        HttpConnectionParams.setSoTimeout(httpParams, timeoutMs);

        SchemeRegistry registry = new SchemeRegistry();
        registry.register(new Scheme("http", new PlainSocketFactory(), 80));
        registry.register(new Scheme("https", SSLSocketFactory.getSocketFactory(), 443));

        ThreadSafeClientConnManager manager = new ThreadSafeClientConnManager(httpParams, registry);
        HttpClient httpClient = new DefaultHttpClient(manager, httpParams);

        return httpClient.execute(httpRequest);
    }

    private void addHeaders(HttpUriRequest httpRequest, Map<String, String> headers) {
        for (String key : headers.keySet()) {
            httpRequest.setHeader(key, headers.get(key));
        }
    }

    private static void setMultiPartBody(HttpEntityEnclosingRequestBase httpRequest,
            Request<?> request) throws AuthFailureError {
        if (request instanceof MultipartRequest) {
            httpRequest.setEntity(((MultipartRequest) request).getEntity());
        }
    }
}

**Comment by 1hakr** [comment]
For this you need to use another library which is Apache HttpClient. which is not efficient for android 4.0 and above. VolleyPlus solves these issue.

**Comment by rambabupudari** [comment]
entity.addBinaryBody("key", data, ContentType.create("image/png"), "image.png");

for this how can i use your library.

i need to add four parameters like above but you have mentioned only three params.

**Comment by 1hakr** [comment]
For adding non file params:
request.addMultipartParam("key", "text/plain", "value");

For adding file as params:
request.addFile("photo", image_path);

**Comment by rambabupudari** [comment]
In  server code they need like key ,byte data, content type,image name in request params.

So how can i achieve this.

**Comment by 1hakr** [comment]
So if the server that you use implements a standard way of accepting multipart form data, the you just need to use the methods above and it will send the required data to the server automatically. The multipart form data is of this format and VolleyPlus does this. If its a custom implementation then you need to customize Multipart Request according to your needs.

http://www.w3.org/TR/html401/interact/forms.html#h-17.13.4

**Comment by lawrence615** [comment]
@1hakr I am getting this error at the mRequestReque.addRequest(request) part;

**The method addRequest(SimpleMultiPartRequest) is undefined for the type RequestQueue**

What am I missing? Tried researching but no success.

**Comment by 1hakr** [comment]
@lawrence615 can you post your code snippet?

**Comment by lawrence615** [comment]
@1hakr Here is my code snippet;

```
SimpleMultiPartRequest request = new SimpleMultiPartRequest(
				Method.POST, AppConstants.postFeedback, reqSuccessListener(),
				reqErrorListener()) {
			@Override
			public Map<String, String> getHeaders() throws AuthFailureError {
				HashMap<String, String> headers = new HashMap<String, String>();
				headers.put("Accept", "application/json");
				// headers.put("Accept", "multipart/form-data");
				// headers.put("Content-Type", "application/json");
				// headers.put("Content-Type", "text/plain");
				headers.put("Content-Length", "302");
				return headers;
			}
		};
		request.addMultipartParam("user_id", "text/plain",
				Integer.toString(getUserId()));
		request.addMultipartParam("tag_id", "text/plain", Integer.toString(16));
		request.addMultipartParam("county_id", "text/plain",
				Integer.toString(getCountyId()));
		request.addMultipartParam("title", "text/plain", title);
		request.addMultipartParam("message", "text/plain", message);

		if (mImageView.getDrawable() != null) {
			File f = createImageFile();
			request.addFile("image_url", f.getAbsolutePath());
			System.out.println("image_url " + f.getAbsolutePath());
		}
		RequestQueue mRequestQueue = Volley.newRequestQueue(getActivity());
		mRequestQueue.add(request);
		mRequestQueue.start();
```

I managed to sort this by using ```mRequestQueue.add(request);``` instead of
```mRequestQueue.addRequest(request);``` as you had used in your example. I have not got it to work yet, am getting error response code 422 (unprocessed entity) but I guess the problem is with my implementation.

Other than images, I also realized that text (from a network request) is also been cached which is a good thing but it becomes a problem when new data is available and cannot be displayed because my ListView has only cached data. 

How can I deal with this?

**Comment by 1hakr** [comment]
Cool, so your initial problem is solved.
For the other problem, are you setting setShouldCache() on your request? This will cache your response permanently. So this has nothing to do with Image caching, which you should be doing with SimpleImageLoader.

**Comment by lawrence615** [comment]
Yes my fierst problem is solved, thanks.

No, I have not used setShouldCache() anywhere, this is how my request looks like;

```
RequestQueue queue = MyVolley.getRequestQueue();
		swipeContainer.setRefreshing(true);

		Uri.Builder builder = Uri.parse(AppConstants.postsUrl).buildUpon();
		builder.appendQueryParameter("tag_id", Integer.toString(tag_id));
		if (county_id != 0) {
			builder.appendQueryParameter("county_id",
					Integer.toString(county_id));
		}

		JsonArrayRequest newsRequest = new JsonArrayRequest(builder.toString(),
				reqSuccessListener(county_id), reqErrorListener(county_id)) {
			@Override
			public Map<String, String> getHeaders() throws AuthFailureError {
				HashMap<String, String> headers = new HashMap<String, String>();
				headers.put("Accept", "application/json");
				return headers;
			}
		};

queue.add(newsRequest);
```

And my ImageLoader
```
mImageLoader = new SimpleImageLoader(mContext,
				R.drawable.white_image_background, null);
		ImageCacheParams cacheParams = new ImageCacheParams(mContext,
				IMAGE_CACHE_DIR);
		cacheParams.setMemCacheSizePercent(0.25f); // Set memory cache to 25% of

		mImageLoader = new SimpleImageLoader(mContext,
				R.drawable.white_image_background, cacheParams);
mImageLoader.get(postm.getImageUrl(), viewHolder.imageView);
```

**Comment by lawrence615** [comment]
@1hakr I have managed to sort  the second problem by adding this line ```newsRequest.setShouldCache(false);	```
Thanks again.

**Comment by 1hakr** [comment]
@lawrence615 you are welcome

**Comment by brooksgod** [comment]
i met a problem.content can send success.but attach image can not send sucess.please help...

  private void publicWeiboTask() {
        RequestQueue requestQueue = PPUApplication.getRequestQueue();
        requestQueue.add(simpleMultiPartRequest());
    }

    private SimpleMultiPartRequest simpleMultiPartRequest() {
        String url = Constants.API_APP_PUBLIC_WEIB_PLUS_IMAGE;
        SimpleMultiPartRequest simpleMultiPartRequest = new SimpleMultiPartRequest(Request.Method.POST,
                url,
                createMyReqSuccessListener(),
                createMyReqErrorListener());

        simpleMultiPartRequest.addMultipartParam("body", "text/plain", mEditText.getText().toString());
        simpleMultiPartRequest.addMultipartParam("type", "text/plain", "postImage");
        simpleMultiPartRequest.addMultipartParam("attach_type", "text/plain", "image");

        simpleMultiPartRequest.addFile("image", mImagePaths.get(0));

        return simpleMultiPartRequest;
    }

**Comment by dotjavafile** [comment]
All file type is getting sent as application/octate-stream which is getting 302 redirected by my server need a way to set content type of the image. Can you show us a way to override your addFile method so we can add contenttype ass well. Or in addMultipartParam where we can add content type but not the file
