### ISSUE TITLE
Conflict with Google Place API

### ISSUE THREAD

**Issue by Wonkyung-LEE** [DWorkS/VolleyPlus#87]
google place 2.3.0 api look like have volley own. 

so, on gradle build process conflict down with embed volley of google-api.

**Comment by rafayrao97** [comment]
I had the same issue did you find solution ?kindly let me know this is the do or die situation for me.

**Comment by rafayrao97** [comment]
> google place 2.3.0 api look like have volley own.
> 
> so, on gradle build process conflict down with embed volley of google-api.


I had the same issue did you find solution ?kindly let me know this is the do or die situation for me

**Comment by Wonkyung-LEE** [comment]
I stoped using lib for problem solve.
And i use own implementation valley multipart request class.
