### ISSUE TITLE
ListView: ImageView display previous image before display correct image

### ISSUE THREAD

**Issue by cuagia** [DWorkS/VolleyPlus#9]
The problem I faced like these:
http://stackoverflow.com/questions/26442252/listview-shows-images-in-wrong-positions-when-scrolling?rq=1
http://stackoverflow.com/questions/27390646/imageviews-in-android-listview-are-showing-previously-loaded-images
Hope you update your code soon :)

**Comment by 1hakr** [comment]
Please try the example here https://github.com/DWorkS/VolleyPlus/blob/master/sample/src/com/volley/demo/SimpleCacheFragment.java .This should solve the issue. The library doesnt provide you with Handling image in Adapter functionality. You need to do it yourself.
